var productionUnits =
{
    '1' : {
        'id': 1,
        'name': 'Intern Kitties',
        'description': 'Makes 0.2 Goo/s',
        'image': 'img/internkitty.png',
        'cost': '??',
		'unitTotal': '-',
        'numOwned': 0,
        'maxOwned': 0,
        'upgradeText1': '+0.1 Base Prod.',
        'upgradeCost1': '??',
        'upgradeImage1': 'img/goo_plus.png',
        'upgradeText2': '+50% Prod.',
        'upgradeCost2': '??',
        'upgradeImage2': 'img/goo_percentage.png',
        'upgradeText3': '999 Max Units',
        'upgradeCost3': '??',
        'upgradeImage3': 'img/unit_cap.png',
		'upgradesAvailable1': 0,
		'upgradesPurchased1': 0,
		'upgradesAvailable2': 0,
		'upgradesPurchased2': 0,
		'upgradesAvailable3': 0,
		'upgradesPurchased3': 0,
        'upgrade1Available': false,
        'upgrade2Available': false,
        'upgrade3Available': false
    },
    '2' : {
        'id': 2,
        'name': 'Graduate Gerbils',
        'description': 'Makes 0.5 Goo/s',
        'image': 'img/graduategerbil.png',
        'cost': '??',
		'unitTotal': '-',
        'numOwned': 0,
        'maxOwned': 0,
        'upgradeText1': '+0.1 Base Prod.',
        'upgradeCost1': '??',
        'upgradeImage1': 'img/goo_plus.png',
        'upgradeText2': '+50% Prod.',
        'upgradeCost2': '??',
        'upgradeImage2': 'img/goo_percentage.png',
        'upgradeText3': '999 Max Units',
        'upgradeCost3': '??',
        'upgradeImage3': 'img/unit_cap.png',
		'upgradesAvailable1': 0,
		'upgradesPurchased1': 0,
		'upgradesAvailable2': 0,
		'upgradesPurchased2': 0,
		'upgradesAvailable3': 0,
		'upgradesPurchased3': 0,
        'upgrade1Available': false,
        'upgrade2Available': false,
        'upgrade3Available': false
    },
    '3' : {
        'id': 3,
        'name': 'Lab Rats',
        'description': 'Makes 10 Goo/s',
        'image': 'img/labrat.png',
        'cost': '??',
		'unitTotal': '-',
        'numOwned': 0,
        'maxOwned': 0,
        'upgradeText1': '+0.1 Base Prod.',
        'upgradeCost1': '??',
        'upgradeImage1': 'img/goo_plus.png',
        'upgradeText2': '+50% Prod.',
        'upgradeCost2': '??',
        'upgradeImage2': 'img/goo_percentage.png',
        'upgradeText3': '999 Max Units',
        'upgradeCost3': '??',
        'upgradeImage3': 'img/unit_cap.png',
		'upgradesAvailable1': 0,
		'upgradesPurchased1': 0,
		'upgradesAvailable2': 0,
		'upgradesPurchased2': 0,
		'upgradesAvailable3': 0,
		'upgradesPurchased3': 0,
        'upgrade1Available': false,
        'upgrade2Available': false,
        'upgrade3Available': false
    },
    '4' : {
        'id': 4,
        'name': 'PhD. Ducks',
        'description': 'Makes 1 Goo/s',
        'image': 'img/phdduck.png',
        'cost': '??',
		'unitTotal': '-',
        'numOwned': 0,
        'maxOwned': 0,
        'upgradeText1': '+0.1 Base Prod.',
        'upgradeCost1': '??',
        'upgradeImage1': 'img/goo_plus.png',
        'upgradeText2': '+50% Prod.',
        'upgradeCost2': '??',
        'upgradeImage2': 'img/goo_percentage.png',
        'upgradeText3': '999 Max Units',
        'upgradeCost3': '??',
        'upgradeImage3': 'img/unit_cap.png',
		'upgradesAvailable1': 0,
		'upgradesPurchased1': 0,
		'upgradesAvailable2': 0,
		'upgradesPurchased2': 0,
		'upgradesAvailable3': 0,
		'upgradesPurchased3': 0,
        'upgrade1Available': false,
        'upgrade2Available': false,
        'upgrade3Available': false
    },
    '5' : {
        'id': 5,
        'name': 'Prof. Penguin',
        'description': 'Makes 2 Goo/s',
        'image': 'img/penguinprofessor.png',
        'cost': '??',
		'unitTotal': '-',
        'numOwned': 0,
        'maxOwned': 0,
        'upgradeText1': '+0.1 Base Prod.',
        'upgradeCost1': '??',
        'upgradeImage1': 'img/goo_plus.png',
        'upgradeText2': '+50% Prod.',
        'upgradeCost2': '??',
        'upgradeImage2': 'img/goo_percentage.png',
        'upgradeText3': '999 Max Units',
        'upgradeCost3': '??',
        'upgradeImage3': 'img/unit_cap.png',
		'upgradesAvailable1': 0,
		'upgradesPurchased1': 0,
		'upgradesAvailable2': 0,
		'upgradesPurchased2': 0,
		'upgradesAvailable3': 0,
		'upgradesPurchased3': 0,
        'upgrade1Available': false,
        'upgrade2Available': false,
        'upgrade3Available': false
    },
    '6' : {
        'id': 6,
        'name': 'Biochem. Badgers',
        'description': 'Makes 4 Goo/s',
        'image': 'img/biochembadger.png',
        'cost': '??',
		'unitTotal': '-',
        'numOwned': 0,
        'maxOwned': 0,
        'upgradeText1': '+0.1 Base Prod.',
        'upgradeCost1': '??',
        'upgradeImage1': 'img/goo_plus.png',
        'upgradeText2': '+50% Prod.',
        'upgradeCost2': '??',
        'upgradeImage2': 'img/goo_percentage.png',
        'upgradeText3': '999 Max Units',
        'upgradeCost3': '??',
        'upgradeImage3': 'img/unit_cap.png',
		'upgradesAvailable1': 0,
		'upgradesPurchased1': 0,
		'upgradesAvailable2': 0,
		'upgradesPurchased2': 0,
		'upgradesAvailable3': 0,
		'upgradesPurchased3': 0,
        'upgrade1Available': false,
        'upgrade2Available': false,
        'upgrade3Available': false
    },
    '7' : {
        'id': 7,
        'name': 'Mad Hares',
        'description': 'Makes 50 Goo/s',
        'image': 'img/madhare.png',
        'cost': '??',
		'unitTotal': '-',
        'numOwned': 0,
        'maxOwned': 0,
        'upgradeText1': '+0.1 Base Prod.',
        'upgradeCost1': '??',
        'upgradeImage1': 'img/goo_plus.png',
        'upgradeText2': '+50% Prod.',
        'upgradeCost2': '??',
        'upgradeImage2': 'img/goo_percentage.png',
        'upgradeText3': '999 Max Units',
        'upgradeCost3': '??',
        'upgradeImage3': 'img/unit_cap.png',
		'upgradesAvailable1': 0,
		'upgradesPurchased1': 0,
		'upgradesAvailable2': 0,
		'upgradesPurchased2': 0,
		'upgradesAvailable3': 0,
		'upgradesPurchased3': 0,
        'upgrade1Available': false,
        'upgrade2Available': false,
        'upgrade3Available': false
    },
    '8' : {
        'id': 8,
        'name': 'Hamster Wheels',
        'description': 'Makes 6 Goo/s',
        'image': 'img/hamsterwheel.png',
        'cost': '??',
		'unitTotal': '-',
        'numOwned': 0,
        'maxOwned': 0,
        'upgradeText1': '+0.1 Base Prod.',
        'upgradeCost1': '??',
        'upgradeImage1': 'img/goo_plus.png',
        'upgradeText2': '+50% Prod.',
        'upgradeCost2': '??',
        'upgradeImage2': 'img/goo_percentage.png',
        'upgradeText3': '999 Max Units',
        'upgradeCost3': '??',
        'upgradeImage3': 'img/unit_cap.png',
		'upgradesAvailable1': 0,
		'upgradesPurchased1': 0,
		'upgradesAvailable2': 0,
		'upgradesPurchased2': 0,
		'upgradesAvailable3': 0,
		'upgradesPurchased3': 0,
        'upgrade1Available': false,
        'upgrade2Available': false,
        'upgrade3Available': false
    }
};

var barracksUnits =
{
    '40' : {
        'id': 40,
        'name': 'Soldier Kitty',
        'description': '10 Att. | 10 Def. | 2M Steal',
        'image': 'img/soldierkitty.png',
        'cost': '??',
		'unitTotal': '-',
        'numOwned': 0,
        'maxOwned': 0,
        'upgradeText1': '+0.1 Base Prod.',
        'upgradeCost1': '??',
        'upgradeImage1': 'img/goo_plus.png',
        'upgradeText2': '+50% Prod.',
        'upgradeCost2': '??',
        'upgradeImage2': 'img/goo_percentage.png',
        'upgradeText3': '999 Max Units',
        'upgradeCost3': '??',
        'upgradeImage3': 'img/unit_cap.png',
		'upgradesAvailable1': 0,
		'upgradesPurchased1': 0,
		'upgradesAvailable2': 0,
		'upgradesPurchased2': 0,
		'upgradesAvailable3': 0,
		'upgradesPurchased3': 0,
        'upgrade1Available': false,
        'upgrade2Available': false,
        'upgrade3Available': false
    },
    '41' : {
        'id': 41,
        'name': 'Knight Kitty',
        'description': '1 Att. | 25 Def. | 1M Steal',
        'image': 'img/knightkitty.png',
        'cost': '??',
		'unitTotal': '-',
        'numOwned': 0,
        'maxOwned': 0,
        'upgradeText1': '+0.1 Base Prod.',
        'upgradeCost1': '??',
        'upgradeImage1': 'img/goo_plus.png',
        'upgradeText2': '+50% Prod.',
        'upgradeCost2': '??',
        'upgradeImage2': 'img/goo_percentage.png',
        'upgradeText3': '999 Max Units',
        'upgradeCost3': '??',
        'upgradeImage3': 'img/unit_cap.png',
		'upgradesAvailable1': 0,
		'upgradesPurchased1': 0,
		'upgradesAvailable2': 0,
		'upgradesPurchased2': 0,
		'upgradesAvailable3': 0,
		'upgradesPurchased3': 0,
        'upgrade1Available': false,
        'upgrade2Available': false,
        'upgrade3Available': false
    },
    '42' : {
        'id': 42,
        'name': 'Archer Kitty',
        'description': '200 Att. | 10 Def. | 10M Steal',
        'image': 'img/archerkitty.png',
        'cost': '??',
		'unitTotal': '-',
        'numOwned': 0,
        'maxOwned': 0,
        'upgradeText1': '+0.1 Base Prod.',
        'upgradeCost1': '??',
        'upgradeImage1': 'img/goo_plus.png',
        'upgradeText2': '+50% Prod.',
        'upgradeCost2': '??',
        'upgradeImage2': 'img/goo_percentage.png',
        'upgradeText3': '999 Max Units',
        'upgradeCost3': '??',
        'upgradeImage3': 'img/unit_cap.png',
		'upgradesAvailable1': 0,
		'upgradesPurchased1': 0,
		'upgradesAvailable2': 0,
		'upgradesPurchased2': 0,
		'upgradesAvailable3': 0,
		'upgradesPurchased3': 0,
        'upgrade1Available': false,
        'upgrade2Available': false,
        'upgrade3Available': false
    },
    '43' : {
        'id': 43,
        'name': 'Fire Kitty',
        'description': '25 Att. | 1 Def. | 4M Steal',
        'image': 'img/firekitty.png',
        'cost': '??',
		'unitTotal': '-',
        'numOwned': 0,
        'maxOwned': 0,
        'upgradeText1': '+0.1 Base Prod.',
        'upgradeCost1': '??',
        'upgradeImage1': 'img/goo_plus.png',
        'upgradeText2': '+50% Prod.',
        'upgradeCost2': '??',
        'upgradeImage2': 'img/goo_percentage.png',
        'upgradeText3': '999 Max Units',
        'upgradeCost3': '??',
        'upgradeImage3': 'img/unit_cap.png',
		'upgradesAvailable1': 0,
		'upgradesPurchased1': 0,
		'upgradesAvailable2': 0,
		'upgradesPurchased2': 0,
		'upgradesAvailable3': 0,
		'upgradesPurchased3': 0,
        'upgrade1Available': false,
        'upgrade2Available': false,
        'upgrade3Available': false
    },
    '44' : {
        'id': 44,
        'name': 'Mace Kitty',
        'description': '20 Att. | 40 Def. | 1M Steal',
        'image': 'img/macekitty.png',
        'cost': '??',
		'unitTotal': '-',
        'numOwned': 0,
        'maxOwned': 0,
        'upgradeText1': '+0.1 Base Prod.',
        'upgradeCost1': '??',
        'upgradeImage1': 'img/goo_plus.png',
        'upgradeText2': '+50% Prod.',
        'upgradeCost2': '??',
        'upgradeImage2': 'img/goo_percentage.png',
        'upgradeText3': '999 Max Units',
        'upgradeCost3': '??',
        'upgradeImage3': 'img/unit_cap.png',
		'upgradesAvailable1': 0,
		'upgradesPurchased1': 0,
		'upgradesAvailable2': 0,
		'upgradesPurchased2': 0,
		'upgradesAvailable3': 0,
		'upgradesPurchased3': 0,
        'upgrade1Available': false,
        'upgrade2Available': false,
        'upgrade3Available': false
    },
    '45' : {
        'id': 45,
        'name': 'Baggage Kitty',
        'description': '20M Steal',
        'image': 'img/baggagekitty.png',
        'cost': '??',
		'unitTotal': '-',
        'numOwned': 0,
        'maxOwned': 0,
        'upgradeText1': '+0.1 Base Prod.',
        'upgradeCost1': '??',
        'upgradeImage1': 'img/goo_plus.png',
        'upgradeText2': '+50% Prod.',
        'upgradeCost2': '??',
        'upgradeImage2': 'img/goo_percentage.png',
        'upgradeText3': '999 Max Units',
        'upgradeCost3': '??',
        'upgradeImage3': 'img/unit_cap.png',
		'upgradesAvailable1': 0,
		'upgradesPurchased1': 0,
		'upgradesAvailable2': 0,
		'upgradesPurchased2': 0,
		'upgradesAvailable3': 0,
		'upgradesPurchased3': 0,
        'upgrade1Available': false,
        'upgrade2Available': false,
        'upgrade3Available': false
    }
};